// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZHf2ZNZJSrQXy7FdboOV6kvPI5M-DivU',
    appId: '1:175170351417:android:1a1261e7f7d3eebc9478e8',
    messagingSenderId: '175170351417',
    projectId: 'plants-care-f3622',
    databaseURL: 'https://plants-care-f3622-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-care-f3622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRSTMQ8Q6LzY5d_1bk9DQj-AHu71kaifA',
    appId: '1:175170351417:ios:1d22ab0ba9eee19f9478e8',
    messagingSenderId: '175170351417',
    projectId: 'plants-care-f3622',
    databaseURL: 'https://plants-care-f3622-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'plants-care-f3622.appspot.com',
    iosBundleId: 'com.app.plantscareorg.plantsCare',
  );
}
